CREATE DATABASE IF NOT EXISTS learning_logs;
USE learning_logs;

DROP TABLE IF EXISTS topics;

CREATE TABLE topics (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);